wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1672665742.370976
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.7.11
      5: 0.13.7
      8:
      - 5
amp:
  desc: null
  value: false
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 5
img_scale:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 1.0e-05
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
